#pragma once
#define WIN32_LEAN_AND_MEAN
#define CURL_STATICLIB

// Add headers that you want to pre-compile here.

#include <Windows.h>
#include <shellapi.h>
#include <unordered_map>
#include <map>
#include <iostream>
#include <iomanip>
#include <functional>
#include <iostream>
#include <sstream>
#include <fstream>
#include <stdlib.h>
#include <stdio.h>
#include <chrono>
#include <thread>
#include <string>
#include <string_view>
#include <cmath>
#include <inttypes.h>
#include <filesystem>
#include <codecvt>
#define CURL_STATICLIB
#include <fstream>
#include <sys/stat.h>
#include <filesystem>
#include <regex>
#include <curl/curl.h>
#include <curlpp/cURLpp.hpp>
#include <curlpp/Options.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Infos.hpp>
#include <wininet.h>
#include <set>
#include <urlmon.h>
#include <unordered_set>
#include <Wininet.h>
#include <shlobj.h>
//#include <dpp/dpp.h>
#include <cstdlib>
#include <future>
#include <chrono>
#include <random>
#include <cassert>
#include <iomanip>
#include <Winsock2.h>
#include <iostream>
#include <system_error>
#include <chrono>
#include <thread>
#include <cstring>
#include <sstream>
#include <array>
#include <algorithm>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <zlib.h>
#include <iomanip>
#include <iphlpapi.h>
#include <WbemCli.h>
#include <d3d11.h>
#include <DirectXMath.h>
#pragma comment(lib, "wbemuuid.lib")
#pragma comment(lib, "IPHLPAPI.lib")
#pragma comment(lib,"Wininet.lib")
#pragma comment(lib,"Urlmon.Lib" )
#pragma comment(lib,"ws2_32.lib")
//#pragma comment(lib,"dpp.lib")

#include "UDP.hpp"
#include "ImGui/includes.h"
#include "json/json/json.h"
#include "ImGui/imgui/ImGuiExtension.h"
#include "ImGui/imgui/Extensions/imgui_extensions.h"
#include "ImGui/imgui/imgui_impl_dx11.h"
#include "Detours/detours.h"
#include "hmac_sha256.h"
#include "base64.h"
#include "RLSDK/se_exception.h"
#include "Network.h"
#include <stdexcept>
#include <openssl/aes.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>